spring:
  datasource:
    url: jdbc:mysql://47.100.214.123:3306/futureQuant?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 111222
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/main/dao/mapper/*.xml

server:
  port: 8080

logging:
  level:
   com.*: debug
